# Generated by Django 4.2.5 on 2023-10-11 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0003_alter_utilisateur_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalle1', models.CharField(default='0', max_length=5)),
                ('libelle', models.CharField(max_length=25)),
                ('intervalle2', models.CharField(default='0', max_length=5)),
                ('couleur', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('cle', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('sexe', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesseurClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.IntegerField(default=0)),
                ('tranche_academique', models.IntegerField(default=0)),
                ('titulaire', models.BooleanField(default=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.professeur')),
            ],
        ),
        migrations.AddField(
            model_name='professeur',
            name='classes',
            field=models.ManyToManyField(through='application_gestion_ecole.ProfesseurClasse', to='application_gestion_ecole.classe'),
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.IntegerField()),
                ('tranche_academique', models.IntegerField()),
                ('note_classe', models.FloatField(null=True)),
                ('note_devoir', models.FloatField(null=True)),
                ('note_composition', models.FloatField(null=True)),
                ('moyenne_sur_20', models.FloatField(null=True)),
                ('note_definitive', models.FloatField(null=True)),
                ('rang', models.CharField(max_length=10)),
                ('appreciation_textuelle', models.CharField(max_length=50)),
                ('appreciation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.appreciation')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Appartenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.eleve')),
            ],
        ),
    ]
