# Generated by Django 4.2.5 on 2023-10-14 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0004_appreciation_classe_eleve_matiere_professeur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AppreciationTextuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=50)),
                ('intervalle_debut', models.FloatField()),
                ('intervalle_fin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClasseEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseMatiereProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField()),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.anneeacademique')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_classe', models.FloatField(blank=True, null=True)),
                ('note_devoir', models.FloatField(blank=True, null=True)),
                ('note_composition', models.FloatField(blank=True, null=True)),
                ('moyenne_sur_20', models.FloatField(blank=True, null=True)),
                ('note_definitive', models.FloatField(blank=True, null=True)),
                ('rang', models.CharField(blank=True, max_length=10)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.anneeacademique')),
                ('appreciation_textuelle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.appreciationtextuelle')),
            ],
        ),
        migrations.CreateModel(
            name='TrancheAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='composition',
            name='appreciation',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='professeurclasse',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='professeurclasse',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='professeurclasse',
            name='professeur',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='cle',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='numero',
        ),
        migrations.AddField(
            model_name='classe',
            name='titulaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.classe'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Appartenance',
        ),
        migrations.DeleteModel(
            name='Appreciation',
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.DeleteModel(
            name='ProfesseurClasse',
        ),
        migrations.AddField(
            model_name='notes',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.eleve'),
        ),
        migrations.AddField(
            model_name='notes',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.matiere'),
        ),
        migrations.AddField(
            model_name='notes',
            name='tranche_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.trancheacademique'),
        ),
        migrations.AddField(
            model_name='classematiereprofesseur',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.classe'),
        ),
        migrations.AddField(
            model_name='classematiereprofesseur',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.matiere'),
        ),
        migrations.AddField(
            model_name='classematiereprofesseur',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classematiereprofesseur',
            name='tranche_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.trancheacademique'),
        ),
        migrations.AddField(
            model_name='classeeleve',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.classe'),
        ),
        migrations.AddField(
            model_name='classeeleve',
            name='eleve',
            field=models.ManyToManyField(to='application_gestion_ecole.eleve'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='classes_en_charges',
            field=models.ManyToManyField(blank=True, through='application_gestion_ecole.ClasseMatiereProfesseur', to='application_gestion_ecole.classe'),
        ),
    ]
