# Generated by Django 4.2.5 on 2023-10-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0006_rename_appreciationtextuelle_appreciation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='NoteEvaluation',
        ),
    ]
