# Generated by Django 4.2.5 on 2023-10-15 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0007_rename_notes_noteevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteevaluation',
            name='classe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application_gestion_ecole.classe'),
        ),
        migrations.AddField(
            model_name='noteevaluation',
            name='professeur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
