# Generated by Django 4.2.5 on 2023-10-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0010_noteevaluation_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classematiereprofesseur',
            name='coefficient',
            field=models.PositiveIntegerField(),
        ),
    ]
