# Generated by Django 4.2.5 on 2023-10-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0011_alter_classematiereprofesseur_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteevaluation',
            name='note_classe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
