# Generated by Django 4.2.5 on 2023-10-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0012_alter_noteevaluation_note_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteevaluation',
            name='note_classe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
