# Generated by Django 4.2.5 on 2023-10-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0013_alter_noteevaluation_note_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteevaluation',
            name='appreciation',
            field=models.CharField(blank=True, default='----nc----', max_length=50),
        ),
        migrations.AlterField(
            model_name='noteevaluation',
            name='rang',
            field=models.CharField(blank=True, default='----nc----', max_length=10),
        ),
    ]
