# Generated by Django 4.2.5 on 2023-10-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0014_alter_noteevaluation_appreciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='est_semestre',
            field=models.BooleanField(default=False),
        ),
    ]
