# Generated by Django 4.2.5 on 2023-10-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0015_classe_est_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteevaluation',
            name='appreciation',
            field=models.CharField(blank=True, default='----nc----', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noteevaluation',
            name='rang',
            field=models.CharField(blank=True, default='----nc----', max_length=10, null=True),
        ),
    ]
