# Generated by Django 4.2.5 on 2023-11-04 20:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0017_alter_noteevaluation_tranche_academique'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eleve',
            name='contact_parent1',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='eleve',
            name='contact_parent2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='eleve',
            name='date_entree_etablissement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eleve_images/'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nationalite',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eleve',
            name='observation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ClasseEleve',
        ),
    ]
