# Generated by Django 4.2.5 on 2023-11-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0018_eleve_adresse_eleve_contact_parent1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='observation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
