# Generated by Django 4.2.5 on 2023-11-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_gestion_ecole', '0020_alter_eleve_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(default='', max_length=100),
        ),
    ]
